@echo off
echo Fixing esbuild platform compatibility issue...
echo Removing existing node_modules directory...
rmdir /s /q node_modules
echo Installing dependencies for the current platform...
npm install
echo Done! You can now run "npm run db:generate"